### ISSUE TITLE
Using BioBert

### ISSUE THREAD

**Issue by rezash1** [dongfang91/Generate-and-Rank-ConNorm#2]
In the paper, it is mentioned that BioBERT has been used for all experiments. Can you please point me to where you are using BioBERT in the code?
Thanks.

**Comment by dongfang91** [comment]
Hello Reza,

We use BioBERT to initialize our BERT based multi-class classifier and BERT based listwise classifier. 

E.g., we will use "biobert" for $model_name_or_path
```
python3.7 run_glue_custom.py \
--model_name_or_path bert-base-uncased \
....
```
